# Generated by Django 3.0.6 on 2020-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200602_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
    ]
